[package]
name = "rougelike_playground"
version = "0.1.0"
authors = ["Jason Jordan <JasonAJordan0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.1" }
